### PR TITLE
Support for Wiimote, with Nunchuk and Classic controller, all genuine…

### PR DESCRIPTION
**Pull request by keithellis74**
… parts except for classic which is a clone

Tom,
I've had a go at writing a class for a genuine Wiimote, including genuine nunchuk and clone classic controller.  The accelerometer axis in the Wiimote are not named correctly, I could not reliably figure out what the third axis was measuring.
I could not see any accelerometer data on the nunchuk
The clone classic controller I have seems to have a faulty left shoulder button, so I intentionally left off the right shoulder button, looks like these might be analogue on the genuine part but I am only getting a binary response.

Hope this is useful, but I found it hard to determine the max/min figures, they scroll past so quick.

### CODE REVIEW

**Comment by tomoinn** [comment]
Keith,

Looks good, but can you change the sname properties to match the current standard ones used by the other controllers? The idea is that we have a set of 'standard names' which map to the most reasonable equivalent on each piece of controller hardware, so for example lx and ly map to analogue axes which are on the left stick of a conventional pad, but maybe use the wiimote nunchuck joystick in your case. The intention is that someone can code assuming there's an analogue stick and a d-pad (for example) and have that work with the most sensible equivalent on any given controller.

**Comment by tomoinn** [comment]
https://approxeng.github.io/approxeng.input/howtouse.html#standard-names has the docs for the currently supported controllers, by way of an example

**Comment by tomoinn** [comment]
Looks much better - one question; the nunchuck Z and C are mapped to 'r1' and 'r2', but 'classic zr' and 'classic zl' are mapped to 'r2' and 'l2', so we have two mappings for r2 and nothing for l1?

**Comment by tomoinn** [comment]
Anyway, I'm going to merge the pull request because it's better to get the code in there in some form than worry too much about details at this point. We can refine later!

**Comment by keithellis74** [comment]
Yes, not sure the right answer on that. You can't have both the classic and nunchuk plugged in at the same time, so there is never two buttons with same mapping

The reason I used r1/r2 on nunchuk is because I hold it in my right hand. I was going to use Wimote B as l1 but when the classic is plugged in the classic B button maps to the same code as the Wiimote B.

Oh and also my l1 on the classic is not working, so I could not get the code. I might have to take it apart and see if I can get it working.  (The classic controller I have is a clone, all the others are genuine Nintendo)

Keith Ellis

**Comment by tomoinn** [comment]
This is all good info, we need a page in the docs for controller with an
appropriate picture and anything like this discussion. The docs build using
sphinx, you could take a look at the current doc source for the controllers
- they're mostly just a directive to copy out the API so any doc comments
you put in the code will be pulled automatically into the generated site,
but you can also explicitly add stuff to the site. I've used a mixture,
when it's class specific I've tended to put the docs in the source files,
when it's more general (like this information on how the combined
controllers work) it should go in its own .rst file.

**Pull request merged**
